# Generated by Django 2.0.4 on 2018-05-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20180529_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_been_played',
            field=models.BooleanField(default=False),
        ),
    ]
