# Generated by Django 2.0.4 on 2018-05-30 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20180529_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Court')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Game')),
            ],
        ),
    ]
